apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service:9090
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: "15s"
          keepCookies: []
          timeRange: null
          grafanaNetAutoLogin: true
